### PR TITLE
Use cmake for building on unix

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
The purpose of this PR is to create a yamlConfig.cmake so that `find_package(yaml)` can be used on Unix platforms.

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/yaml - this is ready for review :).

/cc @wolfv - we need this in RoboStack to unvendor libyaml.

**Comment by jakirkham** [comment]
It might be worth testing that pkg-config and other autotool-related files get installed where expected. This isn't always the case with CMake builds in my experience

**Comment by Tobias-Fischer** [comment]
Indeed no pkg-config files are created in the cmake build.

@traversaro - you are the cmake guru, what is the easiest way to let cmake create pkg-config files? I remember you did this elsewhere, but cannot remember where.

**Comment by traversaro** [comment]
> @traversaro - you are the cmake guru, what is the easiest way to let cmake create pkg-config files? I remember you did this elsewhere, but cannot remember where.

An example of generating `.pc` files from CMake is given in DART:
* https://github.com/dartsim/dart/blob/v6.12.1/CMakeLists.txt#L424
* https://github.com/dartsim/dart/blob/v6.12.1/cmake/dart.pc.in

For other things to check for autotools/cmake equivalence a useful resource is https://conda-forge.org/docs/maintainer/knowledge_base.html#moving-from-an-autotools-build-to-a-cmake-build .

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro - I'll check that out next week

**Comment by Tobias-Fischer** [comment]
Hiya @traversaro - I added the pkg-config generation in https://github.com/conda-forge/yaml-feedstock/pull/20/commits/45164f98297212c9b79babef895f511991b3d365

However the SONAME does not match the one generated by the autotools build (the exported symbols are the same though). What is the easiest way to set the SONAME in the cmake build?

**Comment by traversaro** [comment]
> However the SONAME does not match the one generated by the autotools build (the exported symbols are the same though). What is the easiest way to set the SONAME in the cmake build?

You can set via the [`SOVERSION` target property](https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html):
~~~
set_target_properties(<targetname> PROPERTIES SOVERSION <soversion>)
~~~

**Comment by Tobias-Fischer** [comment]
@traversaro - do you mind having a look at what I've done? I ended up using patchelf as I couldn't figure out how to set the SONAME in the library itself (i.e. not the filename but the SONAME within the library).

**Comment by traversaro** [comment]
> @traversaro - do you mind having a look at what I've done? I ended up using patchelf as I couldn't figure out how to set the SONAME in the library itself (i.e. not the filename but the SONAME within the library).

I realized only later that you were referring to the complete `SONAME` and not just to `SOVERSION`, sorry for the noise. However, your solution seems fine!

**Review by traversaro — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/yaml - now it is really ready for review.

**Comment by jakirkham** [comment]
So some issues were recently encountered with this change ( https://github.com/conda-forge/yaml-feedstock/issues/21 ). PR ( https://github.com/conda-forge/yaml-feedstock/pull/22 ) tries to address them, but falls short. At the moment leaning towards reverting unless someone is able to finish the work.

cc @beckermr

**Comment by ocefpaf** [comment]
Argh. Maybe the best thing to do at the moment is to revert this one, mark the artifacts as broken, and work on #22.

**Comment by jakirkham** [comment]
Yeah Matt took care of marking artifacts broken ( https://github.com/conda-forge/yaml-feedstock/issues/21#issuecomment-994730694 ) ( https://github.com/conda-forge/admin-requests/pull/361 )

Reversion seems like a good idea just to make sure we don't accidentally make a new build that has this issue

Though yeah would be good to fix the CMake issue. The other things above just giving space for people to work :)

Big picture would be nice to figure out how to make these kinds of changes less error prone ( https://github.com/conda-forge/yaml-feedstock/pull/22#issuecomment-995061040 )

**Pull request merged**
